variables:
  GIT_SSL_NO_VERIFY: "true"

before_script:
  ########### Prérequis ###########
  - "/builds/pax-leones/formations/TripAgency/CI_CD/before_jobs.sh"

cache:
  untracked: true

stages:
  - build
  - deploy_to_non_prod_environments
  - deploy_to_prod_environments

build:
  stage: build
  script:
    - "/builds/pax-leones/formations/TripAgency/CI_CD/build.sh"
  artifacts:
    paths:
      - domain/target/TripAgency
      - infrastructure/target
      - application/target
      - exposition/target
    expire_in: 1 day

deploy to DEV:
  stage: deploy_to_non_prod_environments
  script:
    - "/builds/pax-leones/formations/TripAgency/CI_CD/deploy.sh DEV"
  type: deploy
  environment:
    name: dev

deploy to INT:
  stage: deploy_to_non_prod_environments
  script:
    - "/builds/pax-leones/formations/TripAgency/CI_CD/deploy.sh INT"
  type: deploy
  environment:
    name: int